# Путь к конфигу
# на маке: ~/Library/Application\ Support/lazygit/config.yml
# на винде: %LOCALAPPDATA%\lazygit\config.yml (стандартное местоположение, но также можно найти в %APPDATA%\lazygit\config.yml)
# на линуксе: ~/.config/lazygit/config.yml
#
# Оф. док со всей информацией о конфиге: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  theme:
    activeBorderColor:
      - "#fab387"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#fab387"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"

  authorColors:
    "*": "#b4befe"
git:
  paging:
    pager: delta --color-only --paging=never --default-language=go
